### ISSUE TITLE
Bundle chor-js

### ISSUE THREAD

**Issue by jan-ladleif** [bptlab/chor-js#115]
To avoid problems when using and make it less complicated to integrate `chor-js`, we should somehow package/bundle the project.

Babel or Typescript could be used to transpile into a single, compatible source file.

**Comment by jmosen** [comment]
Is there any progress on this issue? An all-in-one pre-packaged version of the library, similar to the pre-packaged version offered by bpmn-js (https://bpmn.io/toolkit/bpmn-js/walkthrough/) would be very handy.

**Comment by jan-ladleif** [comment]
@jmosen We have recently updated our demo application https://github.com/bptlab/chor-js-demo/commit/9c3a902c6855c518c53c69426ba3059fcc00fd01 to use a new build system (Parcel), which apparently could also be used to build pre-packaged versions of chor-js.

@yT0n1 is currently looking into that, but it's hard to give a timeline.

**Comment by jan-ladleif** [comment]
@jmosen We now provide a [pre-packaged version](https://github.com/bptlab/chor-js#a-pre-packaged)!
There is a full example here: https://github.com/bptlab/chor-js/blob/master/docs/prepackaged.html

Let us know if that works for you. :-)

**Comment by jmosen** [comment]
Wow, thank you very much. I was able to integrate ChorJS into my application. Thanks for the quick response!
