### ISSUE TITLE
Can't update a name for an Annotation using `updateLabel` method

### ISSUE THREAD

**Issue by d0na** [bptlab/chor-js#147]
When I try to update (or insert) a name for an Annotation element inside the Modeller (chor-js), using a personal properties handler, it results impossible because is denied the possibility to add or delete more then one character using the method `updateLabel` and it's rendered only the last character typed.  This happen only using the code below and only with the Annotation element. With all the other elements name, for instance with Task, Gateway,.. the code showed below it is working.

I think it is the correct way to update the elements name.

I am using this simple code: 

```
function updateName(name) {
        const modeling = modeler.get('modeling');
        modeling.updateLabel(element,name)
}
```
<img width="380" alt="Screenshot 2019-11-21 at 00 50 40" src="https://user-images.githubusercontent.com/5610407/69288157-0fea5880-0bf9-11ea-9238-2aef6e9e3f98.png">

I am writing on the edit (focused) at the bottom while it is possibile to see only the only one character ('d') rendered in the Annotation name

**Comment by jan-ladleif** [comment]
Hi d0na, thanks for taking the time to write this issue and your interest in `chor-js`! 😄

I looked through the code and do not really see where this could go wrong on our end.
Have you tried replacing `chor-js` with `bpmn-js` for a test so we can rule out that this is an upstream bug?

**Comment by d0na** [comment]
> Have you tried replacing chor-js with bpmn-js for a test so we can rule out that this is an upstream bug?

Yes, you are right. It's a `bpmn-js` issue. 
I will forward the issue on the other project.
Thank's for the hint.

**Comment by jan-ladleif** [comment]
Awesome! Thank you!
