### ISSUE TITLE
Looking for constructor (Viewer/ NavigatedViewer)

### ISSUE THREAD

**Issue by CaptnIglo** [bptlab/chor-js#174]
Hello,
I am not sure if this is the right place to ask this question. I am using `chor-js-modeler.min.js` in my project. I am also using bpmn-js and cmmn-js. Within bpmn-js and cmmn-js you have the option to use a more specific constructor to define a Viewer or NavigatedViewer instance. e.g. `new BpmnJS.Viewer(...)`
I know that there is an explicit library for the viewer (`chor-js-viewer.min.js`). But I was wondering if I could also create a Viewer/NavigatedViewer with the chor-js-modeler-library. 

Greetings
Lucas

**Comment by yT0n1** [comment]
Seems like we forgot a line similar to [this]( https://github.com/bpmn-io/bpmn-js/blob/eb711507d4a3564e2a6da077f686d362b6bd4f28/lib/Modeler.js#L142 ). We will have a look into it and fix it.
